// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX4x_3C9OZk338L32Z0O72svGfPyqLUHg',
    appId: '1:1089493431892:web:e09d35a1ad51c865fa9fc1',
    messagingSenderId: '1089493431892',
    projectId: 'omzet-ku',
    authDomain: 'omzet-ku.firebaseapp.com',
    storageBucket: 'omzet-ku.firebasestorage.app',
    measurementId: 'G-LNNCC7ED22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnyHwPEGI5ITGA2VFKGbEY7vd-z0lxkRU',
    appId: '1:1089493431892:android:08b5b93e8c389cd6fa9fc1',
    messagingSenderId: '1089493431892',
    projectId: 'omzet-ku',
    storageBucket: 'omzet-ku.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHRV2NiotMIzKJq2ytmObIX2Pj5--VfFY',
    appId: '1:1089493431892:ios:02ce52ccf1ed72eefa9fc1',
    messagingSenderId: '1089493431892',
    projectId: 'omzet-ku',
    storageBucket: 'omzet-ku.firebasestorage.app',
    iosBundleId: 'com.example.omzetku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHRV2NiotMIzKJq2ytmObIX2Pj5--VfFY',
    appId: '1:1089493431892:ios:02ce52ccf1ed72eefa9fc1',
    messagingSenderId: '1089493431892',
    projectId: 'omzet-ku',
    storageBucket: 'omzet-ku.firebasestorage.app',
    iosBundleId: 'com.example.omzetku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX4x_3C9OZk338L32Z0O72svGfPyqLUHg',
    appId: '1:1089493431892:web:3158a5c3d7d77358fa9fc1',
    messagingSenderId: '1089493431892',
    projectId: 'omzet-ku',
    authDomain: 'omzet-ku.firebaseapp.com',
    storageBucket: 'omzet-ku.firebasestorage.app',
    measurementId: 'G-Y1XHPL3SYW',
  );
}
